CREATE TABLE items (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  section VARCHAR(255) NOT NULL,
  price DECIMAL(4, 2) NOT NULL
);

CREATE TABLE shoppers (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE orders (
  id SERIAL PRIMARY KEY,
  shopper_id INTEGER REFERENCES shoppers(id) NOT NULL
);

CREATE TABLE orders_items (
  id SERIAL PRIMARY KEY,
  orders_id INTEGER REFERENCES orders(id) NOT NULL,
  items_id INTEGER REFERENCES items(id) NOT NULL
);

